- name: Master node
  hosts: master
  become: true
  strategy: linear
  roles:
    - master
  tags:
    - master

- name: Slave node
  hosts: slave
  become: true
  strategy: linear
  roles:
    - slave
  tags:
    - slave
