---
# tasks file for web

- name: Install EPEL Repo package from standard repo
  yum:
    name: epel-release
    state: present

- name: Install nginx from repo
  yum:
    name: nginx
    state: latest

- name: Create config file from template
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify:
    - Restarting nginx
  tags: 
    restart-nginx

- name: Create index html file from template
  template:
    src: index.html.j2
    dest: /usr/share/nginx/html/index.html
