---
# tasks file for bal

- name: Install EPEL Repo package from standard repo
  yum:
    name: epel-release
    state: present

- name: Install nginx from repo
  yum:
    name: nginx
    state: latest

- name: Copy template-nginx file
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

- name: Restart nginx
  systemd:
    name: nginx
    state: restarted
    enabled: yes
